package myjdbc;

public class ExceptionTest1 {
	public static void main(String[] args)  {
		
		try {
			printHello(-5);
		} catch (MyException e) {
			System.out.println(e.getMessage());
		}
			
	}

	private static void printHello(int count) throws MyException { // throws라는 절로 정의되어 있어서
		if(count<=0) throw new MyException("마이너스는 안되거든요!");
		for(int i=0;i<count;i++) {
			System.out.println("Hello");	
		}
		
		
	}
}

class MyException extends Exception {
	String str;
	MyException(String str){
		
	}
}